'use strict';
const sections=[['overview','Overview'],['team','Research team'],['research','Research progress'],['meetings','Supervisory meetings'],['outputs','Research outputs'],['field','Field highlights'],['logbook','Complete logbook'],['next','Timeline & milestones']];
const domainNames=['Epidemiology and disease control','Family health','Health system management','Environmental health','Occupational health','Health promotion'];
const shortDomains=['Epidemiology','Family health','Health systems','Environmental','Occupational','Health promotion'];
const researchTabs=[['profile','Study profile'],['dataset','Data preparation'],['obj1','Objective 1'],['obj2','Objective 2'],['obj3','Objective 3'],['manuscript','Manuscript']];
const content=document.getElementById('content');
const dialog=document.getElementById('detail');
const state={view:'overview',research:'obj1',domain:'all',query:'',presenting:false,data:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=(text,type='')=>`<span class="badge ${type}">${esc(text)}</span>`;
const goto=(label,view,extra='')=>`<button class="button ghost" type="button" data-view="${view}" ${extra}>${label} <span aria-hidden="true">↗</span></button>`;
const heading=(number,title,intro)=>`<div class="eyebrow">${String(sections.findIndex(x=>x[0]===state.view)+1).padStart(2,'0')} / ${title==='Progress at a glance'?'RESEARCH PROGRESS':esc(sections.find(x=>x[0]===state.view)?.[1]||title)}</div><h1>${esc(title)}</h1>${intro?`<p class="intro">${intro}</p>`:''}`;
const workRows=rows=>`<div class="work-list">${rows.map((r,i)=>`<div class="work-item"><span class="step">${String(i+1).padStart(2,'0')}</span><h3>${r[0]}</h3><p>${r[1]}</p></div>`).join('')}</div>`;
const dl=rows=>`<dl>${rows.map(r=>`<div class="kv"><dt>${r[0]}</dt><dd>${r[1]}</dd></div>`).join('')}</dl>`;
function overview(){return `${heading('01','Progress at a glance','Doctor of Public Health · School of Medical Sciences, Universiti Sains Malaysia')}
  <div class="study-banner"><h2 class="study-title">Assessing and forecasting the impact of ambient air pollution on hospital admissions for cardiorespiratory diseases among the elderly</h2><div class="study-meta"><div><span>Study period</span><strong>2018–2024</strong></div><div><span>Setting</span><strong>Urban Malaysia</strong></div></div></div>
  <div class="section-head"><h2>Three research objectives</h2><span class="meta">Select an objective<br>to explore the work</span></div>
  <div class="three-col">
    <button type="button" class="objective-card" data-research="obj1"><div class="card-top"><span class="num">01</span>${badge('Completed')}</div><h3>Temporal patterns</h3><p>Data preparation, descriptive analysis and temporal assessment.</p></button>
    <button type="button" class="objective-card" data-research="obj2"><div class="card-top"><span class="num">02</span>${badge('Analysis completed','blue')}</div><h3>Short-term associations</h3><p>Hospital-specific models, sensitivity analyses and pooled estimates.</p></button>
    <button type="button" class="objective-card" data-research="obj3"><div class="card-top"><span class="num">03</span>${badge('In development','amber')}</div><h3>Five-year forecast</h3><p>Forecast framework and benchmark modelling underway.</p></button>
  </div>
  <div class="overview-bottom"><div class="panel recognition"><div class="rank">03<span style="font:italic .95rem Georgia;display:block;margin-top:9px">third place</span></div><div><div class="tiny-label">ECRD 2026</div><h3>Research poster recognition</h3><p>Systematic review presented at the East Coast Research Day.</p>${goto('Research outputs','outputs')}</div></div><div class="panel"><div class="portfolio-summary"><div><div class="eyebrow">PKD BESUT</div><h3>Field attachment portfolio</h3><p>Six public health domains</p></div><div class="number">32</div></div>${goto('Explore all logbook entries','logbook')}</div></div>
  <div class="status-line">${badge('Under review','amber')}<div><strong>Systematic review</strong><br>Awaiting the second reviewer’s report and editorial decision.</div></div>`;}

function research(){return `${heading('02','Research progress','A record of completed work, current status and the remaining analytical steps.')}<div class="tabs" role="tablist" aria-label="Research sections">${researchTabs.map(([id,label])=>`<button class="tab" id="tab-${id}" type="button" role="tab" aria-selected="${state.research===id}" aria-controls="research-panel" tabindex="${state.research===id?0:-1}" data-tab="${id}">${label}</button>`).join('')}</div><div id="research-panel" role="tabpanel" aria-labelledby="tab-${state.research}" tabindex="0">${researchBody()}</div>`;}
function researchBody(){
 if(state.research==='profile')return `<section class="panel"><div class="eyebrow">Study focus</div><h2>Multicentre time-series modelling</h2><p class="lead">Ambient air pollution and cardiorespiratory hospital admissions among adults aged 60 years and older in urban Malaysia.</p>${dl([['Candidate','Dr Dzul Hairy bin Mohd Ramlan'],['Study period','2018–2024'],['Ethical clearance','Approval obtained in April 2026']])}</section><div class="section-head"><h2>Research objectives</h2></div>${workRows([['Objective 1','Assess temporal trends in hospital admissions and ambient air pollution.'],['Objective 2','Assess short-term associations between air pollution and admissions.'],['Objective 3','Forecast 5-year trends for cardiorespiratory hospital admissions among the elderly in urban Malaysia using time-series forecasting models.']])}`;
 if(state.research==='dataset')return `<div class="objective-heading"><h2>Data preparation</h2>${badge('Completed')}</div><section class="panel">${workRows([['Data acquisition','Hospital admissions and environmental data obtained.'],['Data cleaning','Eligibility checks, diagnostic coding harmonisation and spatial quality checks completed.'],['Exposure processing','Daily pollutant and meteorological series prepared; missing-data processing completed.'],['Analytical dataset','Linked hospital-level daily time series prepared for Objectives 1–2 and subsequent forecasting.']])}</section>`;
 if(state.research==='obj1')return `<div class="objective-heading"><h2>Objective 1 · Temporal patterns</h2>${badge('Completed')}</div><p class="lead">Describe temporal trends in cardiorespiratory hospital admissions and ambient concentrations of PM₂.₅, PM₁₀, NO₂, SO₂, O₃ and CO from 2018 to 2024.</p><section class="panel">${workRows([['Daily analytical series','Created complete hospital-level time series for admissions, six pollutants and meteorological variables.'],['Descriptive analysis','Prepared summary tables and hospital-specific distributions for the study variables.'],['Temporal assessment','Generated annual and seasonal plots with GAM smoothers for admissions and environmental exposures.'],['Forecast preparation','Prepared the time-series structure and a preliminary STL–ETS benchmark for Objective 3.']])}</section><div class="note-box"><strong>Deliverables ready:</strong> descriptive table, temporal trend figure and cleaned daily analysis dataset.</div>`;
 if(state.research==='obj2')return `<div class="objective-heading"><h2>Objective 2 · Short-term associations</h2>${badge('Analysis completed','blue')}</div><p class="lead">Estimate pollutant-specific immediate and delayed associations with daily admissions using hospital-specific quasi-Poisson distributed lag non-linear models and pooled estimates.</p><section class="panel">${workRows([['Hospital-specific models','Quasi-Poisson DLNM models completed for all four hospitals and six pollutants.'],['Lag summaries','Lag-specific and cumulative lag 0–7 estimates generated using the specified cross-basis.'],['Meta-analytic pooling','Hospital estimates pooled using random-effects REML with heterogeneity statistics.'],['Reporting outputs','Lag 0 table, cumulative table and pooled forest figure prepared for the manuscript.']])}<details><summary>Sensitivity analyses and quality checks</summary><div class="details-body"><p>Two-pollutant models, alternative temporal control, leave-one-hospital-out checks and correlation screening completed. Supporting outputs have been archived for manuscript preparation.</p></div></details></section><div class="note-box">Manuscript reporting and submission preparation are in progress.</div>`;
 if(state.research==='obj3')return `<div class="objective-heading"><h2>Objective 3 · Five-year forecast</h2>${badge('In development','amber')}</div><p class="lead">Forecast cardiorespiratory hospital admissions among older adults for the next five years under a business-as-usual scenario.</p><section class="panel">${workRows([['Freeze the analysis series','Confirm final admissions, pollutant and meteorological inputs.'],['Define validation strategy','Use time-ordered training and holdout periods.'],['Compare candidate models','Evaluate accuracy, residual behaviour and interpretability.'],['Generate BAU forecast','Project annual and seasonal admission burden for five years.'],['Quantify uncertainty','Report prediction intervals and scenario assumptions.']])}</section><div class="note-box amber"><strong>Current benchmark:</strong> a preliminary STL–ETS model has been developed. Final model comparison, selection and forecast validation are still required.</div>`;
 return `<div class="objective-heading"><h2>Objective 1–2 manuscript</h2>${badge('Final revision','amber')}</div><div class="panel"><div class="eyebrow">Target journal: Environmental Research</div><h2 class="study-title">Short-term associations between ambient air pollution and cardiorespiratory hospital admissions among older adults in urban Malaysia: a multicentre distributed lag time-series study</h2><div class="table-wrap" style="margin-top:26px"><table><thead><tr><th>Component</th><th>Work completed</th><th>Status</th></tr></thead><tbody>${[['Introduction','Four-paragraph rationale and regional evidence gap finalised.','Completed'],['Methods','Study design, linkage, imputation, DLNM and sensitivity methods consolidated.','Completed'],['Results','Main tables, forest figure and sensitivity reporting drafted.','Completed'],['Discussion','Interpretation, strengths, limitations and implications drafted.','Completed'],['Submission package','Final references, journal formatting, highlights and cover letter.','In progress']].map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${badge(r[2],r[2]==='In progress'?'amber':'')}</td></tr>`).join('')}</tbody></table></div></div>`;
}

function outputs(){return `<style>.output-image{display:block;width:100%;padding:0;border:0;border-radius:10px;overflow:hidden;cursor:zoom-in;background:#edf1f3;margin:20px 0 12px}.output-image img{display:block;width:100%;height:auto}.award-image{background:#173a4d}.award-image img{max-height:420px;object-fit:contain}.journal-image img{object-fit:contain}.output-image:focus-visible{outline:3px solid #c58b24;outline-offset:4px}.award-location{font-weight:600;color:#f3c673!important}.award-panel .badge{margin-top:8px}.award-panel h2{margin-top:14px}.output-image:hover{filter:brightness(1.04)}</style>${heading('03','Research outputs','Publication progress and scientific dissemination.')}
 <div class="outputs-grid"><section class="panel review-panel"><div class="eyebrow">Systematic review</div><p class="meta"><strong>Environmental Science and Pollution Research</strong></p>${badge('Awaiting reviewer 2','amber')}<h2>Short-term air pollution exposure and cardiorespiratory admissions among older adults</h2><p class="meta">Awaiting the second reviewer’s report and the editorial decision.</p><button type="button" class="output-image journal-image" data-output-photo="journal" aria-label="Enlarge supplied journal profile"><img src="assets/espr-journal.png" alt="Supplied Environmental Science and Pollution Research journal profile showing SJR 2025 0.909 and Q1" loading="lazy"></button><p class="meta">Journal profile · SJR 2025, as shown in the supplied screenshot.</p><div class="review-track"><div class="done">First reviewer<br>Report received</div><div class="waiting">Second reviewer<br>Report awaited</div><div>Editorial<br>Decision pending</div></div></section><section class="panel award-panel"><div class="eyebrow">East Coast Research Day 2026</div><button type="button" class="output-image award-image" data-output-photo="award" aria-label="Enlarge Dr Dzul’s ECRD third-place award photograph"><img src="assets/ecrd-third-place.jpeg" alt="Dr Dzul holding the third-place poster research award at East Coast Research Day 2026 in Kuantan" loading="lazy"></button>${badge('Third place')}<h2>Research poster award</h2><p class="award-location">3rd ECRD 2026 · Kuantan</p><p>Presented the systematic review as part of the DrPH thesis project.</p><div class="meta" style="color:#c8dbe3">Achievement recorded in the progress portfolio.</div></section></div>
 <div class="section-head"><h2>Publication plan</h2><span class="meta">Three manuscripts linked<br>to the thesis objectives</span></div><div class="table-wrap"><table><thead><tr><th>Proposed manuscript</th><th>Thesis component</th><th>Target journal</th><th>Status / timeline</th></tr></thead><tbody>
<tr><td style="min-width:290px">Short-term ambient air pollution and cardiorespiratory hospital admissions among older adults: A systematic review</td><td>Systematic review / evidence base</td><td>Environmental Science and Pollution Research</td><td>${badge('Under review','amber')}<p class="meta">Submitted; awaiting the second reviewer’s report.</p></td></tr>
<tr><td>Short-term associations between ambient air pollution and cardiorespiratory hospital admissions among older adults in urban Malaysia: A multicentre distributed lag time-series study</td><td>Objectives 1 &amp; 2</td><td>Environmental Research</td><td>${badge('Preparation','blue')}<p class="meta">Target submission: 2026</p>${goto('Manuscript progress','research','data-research-tab="manuscript"')}</td></tr>
<tr><td>Forecasting cardiorespiratory hospital admissions among older adults in urban Malaysia under a business-as-usual air-pollution scenario: A five-year projection</td><td>Objective 3 + attributable burden / forecasting</td><td>Environmental Research / Air Quality, Atmosphere &amp; Health</td><td>${badge('Planned','neutral')}<p class="meta">Planned manuscript: 2027</p>${goto('Forecasting progress','research','data-research-tab="obj3"')}</td></tr>
</tbody></table></div><div class="note-box"><strong>Publication strategy:</strong> integrate attributable number (AN) and attributable fraction (AF) into the forecasting manuscript to connect the association analysis with future burden. No separate AN/AF manuscript is planned. Proposed titles and journal targets remain subject to supervisory review and the final forecasting design.</div>
<div class="section-head"><h2>Conference &amp; research dissemination plan</h2><span class="meta">Selected presentation targets</span></div><div class="two-col"><section class="panel"><div class="eyebrow">Regional research presentation</div><h2>ICOEH6 2027</h2><p class="meta">6th International Scientific Conference on Occupational &amp; Environmental Health</p>${badge('Planned','blue')}<p style="margin-top:18px"><strong>25–26 March 2027 · Ha Long, Vietnam</strong></p><p><strong>Proposed output:</strong> Objectives 1–2 — temporal patterns and short-term air-pollution–admission associations.</p><p class="meta">Relevant theme: environmental pollution and public health. Participation is subject to the available abstract submission route, acceptance, supervisory agreement and funding.</p><a class="button small" href="https://icoeh2027.com/" target="_blank" rel="noopener noreferrer">Official conference website ↗</a></section><section class="panel"><div class="eyebrow">Priority international presentation</div><h2>ISEE 2027 · 39th Annual Conference</h2>${badge('Planned','blue')}<p style="margin-top:18px"><strong>5–8 September 2027 · Kota Kinabalu, Malaysia</strong></p><p><strong>Proposed output:</strong> final Objective 2 / Objective 3 findings.</p><p class="meta">Subject to abstract acceptance, supervisory agreement and funding.</p><a class="button small" href="https://www.iseepi.org/" target="_blank" rel="noopener noreferrer">Official conference announcement ↗</a></section></div><p class="source-note">Completed dissemination: 3rd East Coast Research Day 2026, Kuantan — third place, research poster (shown above). Conference plans are separate from confirmed participation.</p>`;}


const fieldCards=[
 {key:'audit',image:'audit.jpeg',alt:'Performance audit activity documented in the PKD Besut logbook',label:'LEAD AUDITOR',title:'Performance audit and governance',date:'28 July 2026',text:'Coordinated Group 2 audit activities for KPI PPTPA and the National Indicator Approach. Reviewed supporting records and completed Performance Audit Forms.',domain:2,record:23,caption:'KPI PPTPA / NIA performance audit. Source: Logbook Dr Hairy.pdf, PDF pages 198–203.',competency:'Leadership and performance governance'},
 {key:'outbreak',image:'outbreak.jpeg',alt:'Field team during the Pulau Perhentian foodborne outbreak investigation',label:'OUTBREAK RESPONSE',title:'Field investigation and control',date:'21 May and 26–27 July 2026',text:'Led the Besut CDC team during the measles response in Marang. Investigated the foodborne outbreak in Pulau Perhentian through active case detection, line listing and environmental assessment.',domain:0,record:8,caption:'Pulau Perhentian foodborne outbreak investigation, 26–27 July 2026. Source: Logbook Dr Hairy.pdf, PDF pages 180–185.',competency:'Epidemiology and disease control'},
 {key:'prolab',image:'prolab.jpeg',alt:'Dr Dzul presenting occupational safety training for school laboratory assistants',label:'INVITED SPEAKER',title:'Occupational health: ProLabCare',date:'27 July 2026',text:'Delivered occupational safety and hazard-management training for school laboratory assistants. Covered HIRARC, chemical and biological hazards, PPE, mercury spills and emergency response.',domain:4,record:29,caption:'ProLabCare training, PPD Besut, 27 July 2026. Source: Logbook Dr Hairy.pdf, PDF pages 192–197.',competency:'Occupational risk communication'},
 {key:'training',image:'training.jpeg',alt:'NMRR and MREC research governance workshop at KK Kota Putera',label:'PRESENTER & FACILITATOR',title:'Training and capacity development',date:'16 April and 22 June 2026',text:'Delivered guidance on NMRR registration, MREC requirements and ethics documents. Taught Emergency Medical Team roles, deployment and operational coordination at the district disaster course.',domain:2,record:19,caption:'NMRR / MREC workshop, KK Kota Putera, 16 April 2026. Source: Logbook Dr Hairy.pdf, PDF pages 92–96.',competency:'Research governance and emergency preparedness'}
];
function field(){return `${heading('04','PKD Besut field attachment','Selected activities with operational, leadership and teaching responsibilities.')}<div class="field-grid">${fieldCards.map(f=>`<article class="field-card ${f.key}"><button class="image-button" type="button" data-photo="${f.key}" aria-label="Enlarge photograph: ${f.title}"><img src="assets/${f.image}" alt="${f.alt}" loading="lazy" width="640" height="400"><span class="expand-label">View photograph ⛶</span></button><div class="field-content"><div class="eyebrow">${f.label}</div><h2>${f.title}</h2><div class="field-meta">${f.date}</div><p>${f.text}</p><p class="meta"><strong>Competency:</strong> ${f.competency}</p><button class="button small" data-field-domain="${f.domain}" type="button">Related logbook entries <span aria-hidden="true">↗</span></button></div></article>`).join('')}</div><div class="source-note">The disaster course is dated 22 June in the detailed report and 21 June in the logbook summary. Both records are flagged in the complete register.</div>`;}

function logbook(){return `${heading('05','Complete activity register','March–July 2026 · All 32 logbook entries, organised by public health domain.')}<div class="filters" role="group" aria-label="Filter activities by domain"><button class="filter" type="button" aria-pressed="${state.domain==='all'}" data-domain="all">All entries <span class="filter-count">32</span></button>${domainNames.map((d,i)=>`<button class="filter" type="button" aria-label="${d}" aria-pressed="${state.domain===String(i)}" data-domain="${i}">${shortDomains[i]} <span class="filter-count">${state.data.filter(a=>a.domain===i).length}</span></button>`).join('')}</div><div class="logbook-toolbar"><label class="search-wrap"><span class="search-mark" aria-hidden="true">⌕</span><input type="search" id="activity-search" placeholder="Search activity, location or role" aria-label="Search logbook entries" value="${esc(state.query)}" autocomplete="off"></label><div class="result-count" id="result-count" aria-live="polite"></div></div><div id="activities" class="log-list"></div><p class="source-note">Source: Logbook Dr Hairy.pdf. Dates and roles follow the detailed reports where available. Summary-only entries, two date discrepancies and one unconfirmed role are marked. The Pulau Perhentian supervision and CDC visit is counted once.</p>`;}
function renderActivities(){
 const query=state.query.trim().toLowerCase();
 const rows=state.data.filter(a=>(state.domain==='all'||a.domain===Number(state.domain))&&[a.title,a.role,a.date,domainNames[a.domain]].join(' ').toLowerCase().includes(query));
 document.getElementById('result-count').textContent=`${rows.length} of 32 entries`;
 document.getElementById('activities').innerHTML=rows.length?rows.map(a=>`<article class="activity"><div class="activity-date"><b>ENTRY ${String(a.id).padStart(2,'0')}</b>${esc(a.date)}</div><div class="activity-main"><h3>${esc(a.title)}</h3><div class="activity-domain">${domainNames[a.domain]}</div>${a.flag?badge(a.flag,'note'):''}</div><div class="activity-role">${esc(a.role)}</div><button type="button" class="button small" data-entry="${a.id}" aria-label="Details for ${esc(a.title)}">Details</button></article>`).join(''):`<div class="empty"><h3>No matching entries</h3><p>Try a different activity, location or role.</p><button class="button" id="reset-search" type="button">Clear filters</button></div>`;
}
const ganttRows=[
 {name:'Data collection',range:'Jan–Mar 2026',start:0,end:2,kind:'collection',note:'Original collection window; completion milestone in April 2026.'},
 {name:'Data entry and analysis',range:'Mar–Oct 2026',start:2,end:9,kind:'analysis',note:'Original chart reaches the start of November. Final analysis completion remains a January 2027 milestone.'},
 {name:'Manuscript write-up',range:'Jul and Oct 2026',months:[6,9],kind:'writing',note:'Two manuscript writing windows in the submitted Gantt chart; submission milestone in January 2027.'},
 {name:'Thesis write-up',range:'Jun 2026–May 2027',start:5,end:16,kind:'writing',note:'Continuous thesis drafting and integration through the submission month.'},
 {name:'Thesis submission',range:'May 2027',start:16,end:16,kind:'submission',note:'Final thesis correction and submission milestone.'}
];
const milestoneRows=[
 {date:'April 2026',label:'01',status:'Completed work recorded',tone:'',items:['Ethical clearance obtained from relevant ethics committees','Data collection completed'],actual:'MREC approval dated 14 April 2026 is recorded. Data acquisition and preparation support the completed Objective 1–2 analyses.'},
 {date:'August 2026',label:'02',status:'Progress checkpoint',tone:'blue',items:['Data entry and data cleaning completed','Approximately 70% of statistical analysis completed','Preliminary results generated','Initial manuscript drafting'],actual:'Objective 1 and Objective 2 analyses and manuscript drafting are recorded. The 70% figure is the original August milestone, not a newly measured completion percentage.'},
 {date:'January 2027',label:'03',status:'Planned',tone:'amber',items:['Data analysis completed','Second manuscript submitted for publication','Approximately 50% of thesis write-up completed'],actual:'Complete and validate Objective 3, finalise the manuscript submission work and review integrated thesis chapters.'},
 {date:'May 2027',label:'04',status:'Final target',tone:'amber',items:['Correction of thesis','Final thesis submission'],actual:'Resolve supervisory corrections and complete the final submission package.'}
];
function next(){
 const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar','Apr','May'];
 return `${heading('06','Gantt chart & milestones','January 2026–May 2027 · Original research schedule with the current progress record.')}<div class="timeline-summary"><div><span class="eyebrow">Reporting checkpoint</span><h2>September 2026</h2><p>Objectives 1–2 analysed; Objective 3 in development.</p></div><div><span class="eyebrow">Final submission target</span><h2>May 2027</h2><p>Thesis correction and submission.</p></div></div>
 <div class="section-head"><h2>Research Gantt chart</h2><span class="meta">Select an activity bar<br>for schedule details</span></div>
 <div class="gantt-scroll" role="region" aria-label="Research Gantt chart, January 2026 to May 2027" tabindex="0"><div class="gantt"><div class="gantt-years"><strong>Activity</strong><span style="grid-column:2 / 14">2026</span><span style="grid-column:14 / 19">2027</span></div><div class="gantt-months"><span>Planned window</span>${months.map((m,i)=>`<span class="${i===8?'checkpoint':''}">${m}</span>`).join('')}</div>${ganttRows.map((r,i)=>`<div class="gantt-row"><div class="gantt-label"><strong>${r.name}</strong><small>${r.range}</small></div><div class="gantt-track">${months.map((m,n)=>`<span class="gantt-cell ${n===8?'checkpoint':''}"></span>`).join('')}${(r.months||[r.start]).map(n=>`<button type="button" class="gantt-bar ${r.kind}" style="grid-column:${n+1} / ${r.months?n+2:r.end+2}" data-gantt="${i}" aria-label="${r.name}: ${r.range}"><span>${r.months?'Write-up':r.name}</span></button>`).join('')}</div></div>`).join('')}</div></div><p class="source-note">Bars show the planned activity windows, not percentage completed. September shading marks the reporting checkpoint. Source: supplied “Gantt Chart & Milestone”.</p>
 <div class="section-head"><h2>Research milestones</h2><span class="meta">Expand each checkpoint<br>to compare plan and progress</span></div><div class="milestone-grid">${milestoneRows.map(m=>`<details class="panel milestone" ${m.label==='02'?'open':''}><summary><div><span class="eyebrow">Milestone ${m.label}</span><h3>${m.date}</h3>${badge(m.status,m.tone)}</div></summary><div class="details-body"><strong>Original milestone</strong><ul>${m.items.map(t=>`<li>${t}</li>`).join('')}</ul><div class="note-box"><strong>Progress / next action</strong><p>${m.actual}</p></div></div></details>`).join('')}</div>
 <div class="note-box amber"><strong>Schedule alignment:</strong> the Gantt analysis window ends around October / early November 2026, while the milestone table sets final analysis completion in January 2027. Both are retained from the source for supervisory review. The source does not identify which paper is the “second manuscript”.</div>
 <div class="section-head"><h2>Immediate priorities</h2></div><section class="panel priorities">${[['Objective 1–2 manuscript','Complete references, journal formatting and the submission package.'],['Objective 3','Complete model comparison, time-ordered validation and the five-year forecast before the January milestone.'],['Thesis integration','Consolidate completed methods and analysis chapters toward the January writing checkpoint.'],['Field attachment','Complete reflections and supervisor verification for the 32 recorded activities.']].map((r,i)=>`<div class="priority"><span class="num">0${i+1}</span><div><h3>${r[0]}</h3><p>${r[1]}</p></div></div>`).join('')}</section>`;
}
function openGantt(index){const r=ganttRows[Number(index)];if(!r)return;document.getElementById('detail-content').innerHTML=`<div class="eyebrow">Research schedule</div><h2>${r.name}</h2>${badge(r.range,'blue')}<p class="lead" style="margin-top:24px">${r.note}</p><p class="meta">Planned timing transcribed from the supplied Gantt chart. This bar does not represent actual percentage completion.</p>`;dialog.showModal();}


const teamMembers=[
 {name:'Dr Dzul Hairy bin Mohd Ramlan',role:'Principal Investigator',title:'Doctor of Public Health Candidate',affiliation:'School of Medical Sciences · Universiti Sains Malaysia',image:'team-supervision.png',box:'36 213 520 480',width:2048,height:1147},
 {name:'AP Dr Nik Rosmawati binti Nik Husain',expertise:'Environmental Health Expert',role:'Main Supervisor',title:'Lecturer · Public Health Medicine Specialist',affiliation:'Department of Community Medicine · School of Medical Sciences · Universiti Sains Malaysia',image:'team-supervision.png',box:'782 213 519 480',width:2048,height:1147},
 {name:'Dr Mohd Faiz bin Ibrahim',expertise:'Environmental Health & Time-Series Expert',role:'Co-supervisor',title:'Public Health Medicine Specialist',affiliation:'Environmental Health Research Centre · Institute for Medical Research · National Institutes of Health Malaysia',image:'team-supervision.png',box:'1504 213 497 480',width:2048,height:1147},
 {name:'Dr Siti Nurbaya binti Mohd Nawi',role:'Co-supervisor',title:'Geriatrics',affiliation:'School of Medical Sciences · Universiti Sains Malaysia',image:'team-nurbaya.png',box:'150 105 330 360',width:2048,height:1385},
 {name:'Dr Mohamad Fadli Kharie',expertise:'GIS Expert',role:'Co-researcher',title:'Senior Principal Assistant Director',affiliation:'Ministry of Health Malaysia',image:'team-fadli.png',box:'18 49 502 502',width:2048,height:573}
];
function team(){return `${heading('02','Research team','The investigators, supervisors and collaborators supporting this DrPH research.')}<style>.team-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:20px}.team-card{grid-column:span 2;text-align:center;padding:26px 20px;border-top:3px solid var(--teal)}.team-card:nth-child(n+4){grid-column:span 3}.team-portrait{display:block;width:150px;height:150px;border-radius:50%;overflow:hidden;margin:0 auto 20px;background:#edf3f5}.team-card h2{font-size:1.13rem;line-height:1.45;margin:15px 0 10px}.team-card p{font-size:.85rem;margin:0 0 10px;color:var(--muted)}.team-card .team-title{color:var(--teal);font-weight:600}.team-card details{text-align:left;border:0}.team-card summary{font-size:.8rem;padding:10px 0}.team-card .details-body{font-size:.85rem;padding:0}.team-card:nth-child(n+4) .team-portrait{width:120px;height:120px}@media(max-width:650px){.team-grid{grid-template-columns:1fr}.team-card,.team-card:nth-child(n+4){grid-column:auto}}</style><div class="team-grid">${teamMembers.map(m=>`<article class="panel team-card"><svg class="team-portrait" viewBox="${m.box}" role="img" aria-label="Portrait of ${esc(m.name)}"><image href="assets/${m.image}" width="${m.width}" height="${m.height}"/></svg>${badge(m.role,m.role==='Co-researcher'?'blue':'')}<h2>${esc(m.name)}</h2>${m.expertise?`<p style="font-weight:650;color:var(--teal);margin:0 0 12px">${esc(m.expertise)}</p>`:""}<p class="team-title">${esc(m.title)}</p><details><summary>Institution / affiliation</summary><div class="details-body">${esc(m.affiliation)}</div></details></article>`).join('')}</div>`;}


const supervisionMeetings=[
 {date:'19 February 2026',time:'2:58 pm MYT',topic:'DOE and MET data analysis',focus:'Discussion of environmental and meteorological data analysis.',evidence:'Recording and chat listed.',note:'Filename timestamp: 2026/02/19 06:58 UTC; converted to Malaysia time.'},
 {date:'5 July 2026',time:'9:10 pm MYT',topic:'Data analysis presentation',focus:'Presentation and discussion of analysis progress and findings with supervisors.',evidence:'Meeting notes listed; meeting photograph supplied.',note:'Notes timestamp: 2026/07/05 13:10 UTC. The supplied photograph is labelled 5 July, 10:24 pm; this is a photo timestamp, not the meeting start time. The photograph shows Dr Dzul, the main supervisor and co-supervisor.'},
 {date:'8 July 2026',time:'9:57 am MYT',topic:'Objective 2: data analysis discussion',focus:'Supervisory discussion of the Objective 2 analysis.',evidence:'Recording, meeting notes and chat listed.',note:'Filename timestamp: 2026/07/07 21:57 EDT; equivalent to 8 July 2026, 9:57 am in Malaysia. Local meeting date follows this conversion.'},
 {date:'Date to confirm',time:'File modified: 12 July',topic:'Objective 2: DLNM and pooled meta-analysis',focus:'Discussion of DLNM analysis and pooled meta-analysis.',evidence:'Recording and notes listed; full filename truncated.',note:'The screenshot shows 12 July in the Date modified column. This is not sufficient to establish the meeting date or time.'},
 {date:'23 July 2026',time:'8:56 pm MYT',topic:'Data analysis presentation',focus:'Presentation and discussion of analysis progress and findings.',evidence:'Two recording files, meeting notes and two chat files listed.',note:'Filename timestamp: 2026/07/23 20:56 GMT+08:00. Multiple files with the same meeting title and timestamp are grouped as one session.'}
];
function meetings(){return `${heading('04','Supervisory meetings','Google Meet · Discussions on data analysis, findings and research progress.')}<div class="timeline-summary"><div><span class="eyebrow">Regular research supervision</span><h2>Analysis review & discussion</h2><p>Recorded meeting topics from February and July 2026.</p></div><div><span class="eyebrow">Supervisory team</span><h2>Main & co-supervisor</h2><p>AP Dr Nik Rosmawati binti Nik Husain<br>Dr Mohd Faiz bin Ibrahim</p></div></div><div class="section-head"><h2>Meeting register</h2><span class="meta">Times shown in<br>Malaysia time (MYT)</span></div><div class="table-wrap"><table><thead><tr><th>Date / time</th><th>Discussion topic</th><th>Supporting record</th></tr></thead><tbody>${supervisionMeetings.map(m=>`<tr><td style="min-width:170px">${m.date}<br><span class="meta">${m.time}</span></td><td style="min-width:270px"><strong>${m.topic}</strong><p class="meta" style="margin:8px 0">${m.focus}</p></td><td style="min-width:250px"><span class="meta">${m.evidence}</span><details><summary>Record details</summary><div class="details-body">${m.note}</div></details></td></tr>`).join('')}</tbody></table></div><p class="source-note">Source: supplied Google Drive Meet Recordings screenshot and 5 July meeting photograph. Topics are transcribed from the visible records; specific decisions and action items are not available in these screenshots.</p>`;}

const renderers={overview,team,research,meetings,outputs,field,logbook,next};
function render(){
 document.getElementById('navigation').innerHTML=sections.map(([id,label],i)=>`<a href="#${id}" class="nav-link ${id===state.view?'active':''}" ${id===state.view?'aria-current="page"':''}><span class="index">0${i+1}</span><span>${label}</span></a>`).join('');
 content.innerHTML=`<div class="view-enter">${renderers[state.view]()}</div>`;
 if(state.view==='logbook')renderActivities();
 document.title=`${sections.find(s=>s[0]===state.view)[1]} · Dr Dzul DrPH`;
 updatePresentation();
}
function setView(view,{scroll=true}={}){if(!renderers[view])view='overview';state.view=view;history.replaceState(null,'','#'+view);render();if(scroll)window.scrollTo({top:0,behavior:'instant'});}
function openEntry(id){
 const a=state.data.find(x=>x.id===Number(id));if(!a)return;
 const notes=a.notes.map(n=>`<p>${esc(n)}</p>`).join('');
 document.getElementById('detail-content').innerHTML=`<div class="dialog-title-row"><div class="eyebrow" style="margin:0">LOGBOOK ENTRY ${String(a.id).padStart(2,'0')}</div>${a.flag?badge(a.flag,'note'):''}</div><h2>${esc(a.title)}</h2>${dl([['Date',esc(a.date)],['Domain',domainNames[a.domain]],['Recorded role',esc(a.role)]])}${notes?`<div class="note-box ${a.flag?'amber':''}">${notes}</div>`:''}<div class="dialog-source"><strong>Source:</strong> Logbook Dr Hairy.pdf<br>PDF pages ${esc(a.pages)}. Page references refer to the PDF, rather than its printed page numbers.</div>`;
 dialog.showModal();
}
function openOutputPhoto(key){const p=key==='journal'?{title:'Environmental Science and Pollution Research',file:'espr-journal.png',caption:'Journal profile supplied for this report. SJR 2025: 0.909; Q1 shown in the screenshot. Manuscript remains under review; awaiting reviewer 2.'}:{title:'Third place · ECRD 2026, Kuantan',file:'ecrd-third-place.jpeg',caption:'Dr Dzul Hairy bin Mohd Ramlan with the third-place poster research award at East Coast Research Day 2026 in Kuantan.'};document.getElementById('detail-content').innerHTML=`<h2>${p.title}</h2><img class="dialog-image" src="assets/${p.file}" alt="${p.title}"><p class="dialog-caption">${p.caption}</p>`;dialog.showModal();}
function openPhoto(key){const f=fieldCards.find(x=>x.key===key);if(!f)return;document.getElementById('detail-content').innerHTML=`<div class="eyebrow">FIELD ATTACHMENT</div><h2>${f.title}</h2><img class="dialog-image" src="assets/${f.image}" alt="${f.alt}"><p class="dialog-caption">${f.caption}</p>`;dialog.showModal();}
function updatePresentation(){const i=sections.findIndex(s=>s[0]===state.view);document.getElementById('present-position').textContent=`${i+1} / ${sections.length}`;document.getElementById('present-prev').disabled=i===0;document.getElementById('present-next').disabled=i===sections.length-1;}
async function present(){state.presenting=true;document.body.classList.add('presenting');document.querySelector('.presentation-controls').hidden=false;window.scrollTo(0,0);try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();}catch(_){/* Presentation layout also works when fullscreen is unavailable. */}updatePresentation();}
async function exitPresent(){state.presenting=false;document.body.classList.remove('presenting');document.querySelector('.presentation-controls').hidden=true;if(document.fullscreenElement&&document.exitFullscreen)try{await document.exitFullscreen();}catch(_){};document.getElementById('present').focus();}
function shiftSection(direction){const i=sections.findIndex(s=>s[0]===state.view),target=sections[i+direction];if(target)setView(target[0]);}
document.addEventListener('click',e=>{
 const el=e.target.closest('button,a');if(!el)return;
 if(el.classList.contains('nav-link')){e.preventDefault();setView(el.hash.slice(1));return;}
 if(el.classList.contains('brand')){e.preventDefault();setView('overview');return;}
 if(el.dataset.research){state.research=el.dataset.research;setView('research');return;}
 if(el.dataset.view){if(el.dataset.researchTab)state.research=el.dataset.researchTab;setView(el.dataset.view);return;}
 if(el.dataset.tab){state.research=el.dataset.tab;setView('research',{scroll:false});document.getElementById('tab-'+state.research).focus();return;}
 if(el.dataset.domain!==undefined){state.domain=el.dataset.domain;setView('logbook',{scroll:false});document.querySelector(`[data-domain="${state.domain}"]`).focus();return;}
 if(el.dataset.fieldDomain!==undefined){state.domain=el.dataset.fieldDomain;state.query='';setView('logbook');return;}
 if(el.dataset.gantt!==undefined){openGantt(el.dataset.gantt);return;}
 if(el.dataset.outputPhoto){openOutputPhoto(el.dataset.outputPhoto);return;}
 if(el.dataset.entry){openEntry(el.dataset.entry);return;}
 if(el.dataset.photo){openPhoto(el.dataset.photo);return;}
 if(el.classList.contains('dialog-close')){dialog.close();return;}
 if(el.id==='reset-search'){state.domain='all';state.query='';setView('logbook',{scroll:false});document.getElementById('activity-search').focus();return;}
 if(el.id==='present'){present();return;}
 if(el.id==='present-exit'){exitPresent();return;}
 if(el.id==='present-prev'){shiftSection(-1);return;}
 if(el.id==='present-next'){shiftSection(1);return;}
 if(el.id==='retry'){location.reload();}
});
document.addEventListener('input',e=>{if(e.target.id==='activity-search'){state.query=e.target.value;renderActivities();}});
document.addEventListener('keydown',e=>{
 if(dialog.open)return;
 if(e.target.matches('[role="tab"]')&&['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const i=researchTabs.findIndex(t=>t[0]===state.research);let n=e.key==='Home'?0:e.key==='End'?researchTabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+researchTabs.length)%researchTabs.length;state.research=researchTabs[n][0];setView('research',{scroll:false});document.getElementById('tab-'+state.research).focus();return;}
 if(!state.presenting||e.target.matches('input,textarea,select'))return;
 if(e.key==='Escape'){exitPresent();return;}
 if(e.key==='ArrowRight'){e.preventDefault();shiftSection(1);}
 if(e.key==='ArrowLeft'){e.preventDefault();shiftSection(-1);}
});
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&state.presenting)exitPresent();});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
window.addEventListener('hashchange',()=>{if(state.data)setView(location.hash.slice(1));});
fetch('activities.json').then(r=>{if(!r.ok)throw new Error('Activity register could not be loaded');return r.json();}).then(data=>{if(data.length!==32)throw new Error('Incomplete activity register');state.data=data;setView(location.hash.slice(1)||'overview');}).catch(()=>{content.innerHTML='<div class="error-panel"><h1>Report could not load</h1><p>The activity register is temporarily unavailable. Please try again.</p><button class="button primary" id="retry" type="button">Reload report</button></div>';});
